<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Airway Bill</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
        }

        .header {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .content {
            font-size: 16px;
        }

        .footer {
            margin-top: 30px;
            font-size: 14px;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        Airway Bill for Order #{{ $warehouse_number }}
    </div>
    <div class="content">
        <p><strong>Order ID:</strong> {{ $order_id }}</p>
        <p><strong>Total Price:</strong> {{ $total_price }}</p>
    </div>
    <div class="footer">
        Generated by Your Company Name
    </div>
</body>

</html>